/**
 * "From the simulator to the real board": builds a ready-to-compile Quartus II
 * project for the original Terasic/Altera DE2 (Cyclone II EP2C35F672C6) from
 * the design and pin mapping in the DE2 simulator.
 *
 * Cyclone II is supported up to Quartus II 13.0 SP1 (Web Edition), so the
 * project targets that version.
 */
import { pinDictionary } from './parser/de2Dictionary';
import type { ParsedPort } from './parser/pinParser';
import { expandTarget, parseVirtualComponent } from '../board/virtualComponents';

/** DE2 character LCD pins (DE2 User Manual, LCD module table). */
const LCD_PINS: Record<string, string> = {
  'LCD_DATA[0]': 'PIN_J1', 'LCD_DATA[1]': 'PIN_J2', 'LCD_DATA[2]': 'PIN_H1', 'LCD_DATA[3]': 'PIN_H2',
  'LCD_DATA[4]': 'PIN_J4', 'LCD_DATA[5]': 'PIN_J3', 'LCD_DATA[6]': 'PIN_H4', 'LCD_DATA[7]': 'PIN_H3',
  LCD_RW: 'PIN_K4', LCD_EN: 'PIN_K3', LCD_RS: 'PIN_K1', LCD_ON: 'PIN_L4', LCD_BLON: 'PIN_K2',
};

/** Board signal name (e.g. "SW[3]", "HEX0[6]", "CLOCK_50") → DE2 FPGA pin. */
const BOARD_PIN: Record<string, string> = (() => {
  const map: Record<string, string> = { ...LCD_PINS };
  for (const [pin, signal] of Object.entries(pinDictionary)) {
    if (pin.startsWith('PIN_')) map[signal.toUpperCase()] = pin;
  }
  return map;
})();

export interface PinAssignment {
  /** Quartus target, e.g. "SW[3]" or "LEDR0". */
  target: string;
  pin: string;
  /** Board resource, e.g. "SW[3]". */
  board: string;
}

function lcdBoardName(raw: string): string | null {
  const n = raw.trim().toUpperCase().replace(/_(\d+)$/, '[$1]').replace(/^LCD_DATA(\d)$/, 'LCD_DATA[$1]');
  return LCD_PINS[n] ? n : null;
}

/** Resolve every mapped port bit to a physical DE2 pin. */
export function resolvePinAssignments(
  mappings: ParsedPort[],
  portWidths: Record<string, number>,
): { assignments: PinAssignment[]; unresolved: string[] } {
  const assignments: PinAssignment[] = [];
  const unresolved: string[] = [];
  const seen = new Set<string>();
  const add = (a: PinAssignment) => {
    if (seen.has(a.target)) return;
    seen.add(a.target);
    assignments.push(a);
  };

  for (const m of mappings) {
    if (!m.portName) continue;
    const base = m.portName.replace(/\[.*$/, '');
    const width = Math.max(1, portWidths[base] ?? 1);
    // The simulator drives a port named CLOCK_50 from the board clock even
    // when the mapping leaves it blank; the real board needs its pin.
    const vc = m.virtualComponent || (/^CLOCK_50$/i.test(base) ? 'CLOCK_50' : '');

    // An explicit pin from an imported .qsf wins.
    if (m.physicalPin && /^PIN_/i.test(m.physicalPin) && !vc) {
      add({ target: m.portName, pin: m.physicalPin.toUpperCase(), board: pinDictionary[m.physicalPin.toUpperCase()] ?? m.physicalPin });
      continue;
    }

    const lcd = vc ? lcdBoardName(vc) : null;
    if (lcd) {
      add({ target: m.portName, pin: LCD_PINS[lcd], board: lcd });
      continue;
    }
    if (/^LCD_DATA$/i.test(vc)) {
      for (let i = 0; i < Math.min(width, 8); i++) add({ target: `${m.portName}[${i}]`, pin: LCD_PINS[`LCD_DATA[${i}]`], board: `LCD_DATA[${i}]` });
      continue;
    }

    const target = parseVirtualComponent(vc);
    if (!target) {
      if (m.physicalPin && /^PIN_/i.test(m.physicalPin)) {
        add({ target: m.portName, pin: m.physicalPin.toUpperCase(), board: vc || m.physicalPin });
      } else if (vc) {
        unresolved.push(m.portName);
      }
      continue;
    }
    for (const { signal, index } of expandTarget(target, m.portName, width)) {
      const board =
        target.family === 'CLOCK_50' ? 'CLOCK_50'
        : target.family === 'HEX' ? `HEX${target.display}[${index}]`
        : `${target.family}[${index}]`;
      const pin = BOARD_PIN[board];
      if (pin) add({ target: signal, pin, board });
      else unresolved.push(signal);
    }
  }
  return { assignments, unresolved };
}

export interface QuartusProjectInput {
  topModule: string;
  source: string;
  mappings: ParsedPort[];
  portWidths: Record<string, number>;
}

export function buildQuartusProject(input: QuartusProjectInput): { files: { name: string; content: string }[]; unresolved: string[]; pinCount: number } {
  const top = input.topModule || 'top';
  const srcName = `${top}.sv`;
  const { assignments, unresolved } = resolvePinAssignments(input.mappings, input.portWidths);
  const usesClock = assignments.some((a) => a.board === 'CLOCK_50');

  const qpf = [
    '# Quartus II project generated by Logic Lab',
    'QUARTUS_VERSION = "13.0"',
    `PROJECT_REVISION = "${top}"`,
    '',
  ].join('\n');

  const qsf = [
    '# Generated by Logic Lab for the Terasic/Altera DE2 board',
    '# Device: Cyclone II EP2C35F672C6 — open with Quartus II 13.0 SP1 Web Edition',
    '',
    'set_global_assignment -name FAMILY "Cyclone II"',
    'set_global_assignment -name DEVICE EP2C35F672C6',
    `set_global_assignment -name TOP_LEVEL_ENTITY ${top}`,
    `set_global_assignment -name SYSTEMVERILOG_FILE ${srcName}`,
    usesClock ? `set_global_assignment -name SDC_FILE ${top}.sdc` : '',
    'set_global_assignment -name RESERVE_ALL_UNUSED_PINS "AS INPUT TRI-STATED"',
    'set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "3.3-V LVTTL"',
    'set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files',
    '',
    '# Pin assignments',
    ...assignments.map((a) => `set_location_assignment ${a.pin} -to ${a.target}`),
    '',
  ].filter((l, i, arr) => l !== '' || arr[i - 1] !== '').join('\n');

  const sdc = [
    '# 50 MHz board clock',
    'create_clock -name CLOCK_50 -period 20.000 [get_ports {CLOCK_50}]',
    'derive_clock_uncertainty',
    '',
  ].join('\n');

  const readme = `${top} — Logic Lab → gerçek DE2 kartı / real DE2 board

TÜRKÇE
1. Quartus II 13.0 SP1 Web Edition'ı kurun (Cyclone II'yi destekleyen son sürüm).
2. ${top}.qpf dosyasını Quartus ile açın.
3. Processing → Start Compilation ile derleyin.
4. DE2'yi USB-Blaster (USB) ile bağlayın, güç verin, RUN/PROG anahtarını RUN'a alın.
5. Tools → Programmer: Hardware Setup'ta USB-Blaster'ı seçin, Mode: JTAG,
   output_files/${top}.sof dosyasını ekleyip Start'a basın.
Pin sayısı: ${assignments.length}${unresolved.length ? `\nAtanamayan portlar (elle ekleyin): ${unresolved.join(', ')}` : ''}

ENGLISH
1. Install Quartus II 13.0 SP1 Web Edition (the last release with Cyclone II support).
2. Open ${top}.qpf in Quartus.
3. Processing → Start Compilation.
4. Connect the DE2 over USB-Blaster, power it on, set RUN/PROG to RUN.
5. Tools → Programmer: select USB-Blaster, Mode JTAG, add output_files/${top}.sof, Start.
Pins assigned: ${assignments.length}${unresolved.length ? `\nUnassigned ports (add by hand): ${unresolved.join(', ')}` : ''}
`;

  const files = [
    { name: `${top}.qpf`, content: qpf },
    { name: `${top}.qsf`, content: qsf },
    { name: srcName, content: input.source },
    { name: 'README.txt', content: readme },
  ];
  if (usesClock) files.splice(2, 0, { name: `${top}.sdc`, content: sdc });
  return { files, unresolved, pinCount: assignments.length };
}
